### ISSUE TITLE
could not handle some H265 files even in -avsw

### ISSUE THREAD

**Issue by devil40xxx** [rigaya/NVEnc#237]
It returned  errors something like: 
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (17564159 > 2194).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 164).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 164).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 165).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 165).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 165).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 165).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 164).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 165).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 164).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 170).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 1688).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 170).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 166).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 176).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 176).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 176).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 561).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 217).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 172).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 173).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 172).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 259).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 279).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 314).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 916).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 335).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 265).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 284).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 234).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 1295).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 334).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 219).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 214).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 1018).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 625).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 239).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (17564159 > 3645).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 2380).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 681).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 582).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 526).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 500).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 462).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 452).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 3380).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 1051).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 446).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 410).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 603).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 530).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 4742).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 844).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 386).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 355).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 6953).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 1286).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 540).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 512).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 9450).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 3060).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 845).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 626).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 11720).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 3079).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 1093).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 981).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 14371).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 4090).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 1357).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 1438).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 17665).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 5167).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 1850).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 1938).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 21345).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 6856).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 2573).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 2623).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 22889).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 3506).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 19562).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 9265).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 5369).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 5878).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (17564159 > 24202).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 18755).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 8040).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 2014).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 2088).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 23560).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 11780).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 5188).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 5626).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 5052).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 6004).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 25017).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 6913).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 3244).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 27221).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 16085).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 9149).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 9151).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 9476).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 8632).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 23684).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 12492).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 6010).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 38600).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 20943).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 13976).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 15286).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 17096).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 17552).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 57453).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 37521).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 93763).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 64381).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 73217).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 63101).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 57879).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 58245).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 54971).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 44620).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 47513).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 49640).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 49609).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 46393).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 37993).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 35680).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 32271).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 24718).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 21758).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (17564159 > 41772).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 21610).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 14529).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 20100).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 10806).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 23644).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 15549).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 8990).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 11732).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 19894).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 10230).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 16318).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 22886).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 11502).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 13292).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 11578).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 10255).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 10169).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 7858).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 7643).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 6935).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 21524).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 8100).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 4831).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 4507).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 4184).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 3337).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 5850).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 15061).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 12406).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 20796).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 10635).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 11490).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 8626).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 9721).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 9893).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 10023).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 4635).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 10192).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 20725).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 9983).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 10358).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 7905).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 9008).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 8889).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 8875).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 4221).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 9059).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (17564159 > 34861).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 10115).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 15274).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 3928).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 3913).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 2479).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 12195).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 3077).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 9811).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 16931).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 10778).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 3656).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 3749).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 6911).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 5626).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 11010).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 9461).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 10100).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 21519).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 16693).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843268 > 13416).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 13843).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 12712).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 14309).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843269 > 14660).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 15082).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 15274).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 22044).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843270 > 19208).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 16995).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 17968).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 17052).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843271 > 17560).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 18090).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 17611).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 19626).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843272 > 22652).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 19489).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 16513).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 17627).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843273 > 22099).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 17484).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 21681).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 25096).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843274 > 21819).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 19334).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 19923).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843275 > 19546).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (17564159 > 39651).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 34819).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 27442).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 24149).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843264 > 25923).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 25894).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 26478).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 26753).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843265 > 25961).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 26507).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 36101).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 30719).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843266 > 27661).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 28154).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 25244).
[hevc @ 0000018249c1c8c0] Invalid NAL unit size (16843267 > 39567).
[hevc @ 0000018253168c00] Invalid NAL unit size (17564159 > 2194).
[hevc @ 0000018253168c00] Error splitting the input into NAL units.
avsw: failed to send packet to video decoder: Invalid data found when processing input.
avsw: Failed to parse HDR metadata header from input.
failed to initialize file reader(s).
Failed to open input file.
--------------------------------------
I notice the problem occurs mutilpe times  recently.

The video files are all played fine in all mainstream x265 player.

The files nvenc can't handle looks like all the same (H265  / smpte st 2086 HDR compatible, profile 5.1) 

Due to my current network environment i can't upload a tester file but there is  a sample file (just downlod the small one ) in magnt link: 
magnet:?xt=urn:btih:f6357ff47bcd817946f666a4c84c57bbd471c80d

**Comment by rigaya** [comment]
Thanks for sharing the file, I've checked it, but the problem was that libavformat was failing to extract proper header, and gets unable to apply hevc_mp4toannexb bitstream filter required for hw decode. You can see this problem also in ffmpeg 4.2 by commandline below, it also stops by error.

ffmpeg -i input.mkv -c:v copy -an -bsf:v hevc_mp4toannexb test.265

Somehow sw decoder seems to work even if we face this problem, so I added workaround switching to sw decoder when this error happens in [NVEnc 5.04](https://github.com/rigaya/NVEnc/releases/tag/5.04).

**Comment by devil40xxx** [comment]
It works in 5.04，thx for the good job.  

And when  running the 64bit build ,it seems like the .ver shows in cmd screen is still 5.03 r1557 - Jun 11 2020 ? :" )  @rigaya

**Comment by rigaya** [comment]
> 5.03 r1557

It's only the version number, just in case I have re-uploaded updating the version number.

**Comment by ValZapod** [comment]
> that libavformat was failing to extract proper header

Is that fixed in master? Maybe open an issue on https://trac.ffmpeg.org/?

**Comment by ValZapod** [comment]
Looks like -bsf:v hevc_mp4toannexb works on all https://ffmpeg.zeranoe.com/builds/ builds including not from master... Hmmm?

**Comment by rigaya** [comment]
I've tested ffmpeg 4.3 build of https://ffmpeg.zeranoe.com/builds/ but still gets the following warning which is causing this problem.

```
[hevc_mp4toannexb @ 0000023d192b5240] No parameter sets in the extradata
```

parameter sets (PPS) is the header is required for hw decoding.

I'll keep this as-is, the work around is working fine.

**Comment by ValZapod** [comment]
@rigaya Issue https://trac.ffmpeg.org/ticket/7799

hevc_mp4toannexb bsf doesn't insert correct parameter sets if they change in-band. For now, you can just use hevc_metadata filter to do the same job:
./ffmpeg -i hevc_after_mp4toannexb_conversion_qp_value_modified.mp4 -bsf:v hevc_metadata -codec:v copy output.hevc

**Comment by rigaya** [comment]
I’ll close this issue, as now NVEnc 7.58 adds support for this situation, now can retrieve header from first packet if not extracted in extra data.
