### ISSUE TITLE
Using "--sub-source" with other params than filename isn't working

### ISSUE THREAD

**Issue by Killua-Zolldyck** [rigaya/NVEnc#481]
Hi there,

I tried to use --sub-source as described in the options section. Using it with filename only, everything's working fine. But when I add additional params like ":metadata=language=jpn" there is no error, but processing the file doesn't start either. Comparing the debug logs of a try with additional params and a try without addiotional params, I've seen that there are 3 lines missing in the log with params. These are:

`avsw: found subtitle stream, stream idx 0, trackID 1.0, ass, frame_size 0, timebase 1/100, delay 0 ms`
`avsw: avcodec subtitle: ass from xxx.ass`

and further down

`Output: Added subtitle track#12289 (stream idx 0) for mux, bitrate 0, codec: copy  , bsf: <none>, disposition: <copy>, metadata: <copy>`

If you need any more information, just let me know.

Best Regards

**Comment by rigaya** [comment]
Thank you for letting me know the issue, seems to be a bug from NVEnc 7.22.

I'll fix it in the next release.

**Comment by Killua-Zolldyck** [comment]
Indeed. v7.21 isn't showing any problems.

**Comment by rigaya** [comment]
Thanks again for reporting, the new [NVEnc 7.24](https://github.com/rigaya/NVEnc/releases/tag/7.24) shall be able to fix this issue.

**Comment by rigaya** [comment]
I'll close this issue as the problem should have been fixed.

**Comment by Killua-Zolldyck** [comment]
Thanks for the fix in v7.24, but there is still an issue left (compared to v7.21). When I use --sub-source with "disposition=forced" I get the error that the option "forced" is unkown. In v7.21 there were no problems with this and the forced flag was set correctly in the resulting mkv. Maybe you want to have a look again?

Best Regards

**Comment by rigaya** [comment]
[NVEnc 7.25](https://github.com/rigaya/NVEnc/releases/tag/7.25) have changed parsing of --sub-source to fix this issue.

**Comment by Killua-Zolldyck** [comment]
Okay, using the options does not result in error messages with v7.25, but it is still not working without issues sometimes (compared to version 7.21, where everything's fine). While using --sub-source with certain ass subtitle files will result in corrupt mkv outputs. Then the audio (aac_mf) does not play and trying to remux the mkv with mkvmerge will bring up an error message that the header data of the audio stream is faulty... Removing the --sub-source file or using anothter one is removing the problem and the mkv result is fine. So it is not really a problem with the audio stream, but the input subtitle file, which is triggering the error. If needed I can provide some files, so you can reproduce the error on your side for investigation.

Best Regards

**Comment by rigaya** [comment]
I cannot figure out what is the actual problem here. I think the input file and the full command line(not partial) might help.

May I ask some questions?

1.
> but it is still not working without issues sometimes

What does “sometimes”actually mean? Does the problem happen depending on the input file? Or does the problem happen randomly?

2.
> Removing the --sub-source file or using anothter one is removing the problem

Could you please give the details of “using another one”?

3.
One more question, does this corrupt mov output problem happen with the previous NVEnc 7.24 (when used without disposition parameter)?

**Comment by Killua-Zolldyck** [comment]
I did some more research. I looks like that the subtitle problem I described before is either a side effect or an additional problem. On versions 7.22 to 7.25 using "aac_mf" audio codec is always leading to a mkv file that cannot be remuxed with mkvmerge again. No matter, if there are any subtitles or not. No matter if the file can be played or not. This problem does not occur up to version 7.21.
