### ISSUE TITLE
SEI_rbsp_stop_one_bit Missing

### ISSUE THREAD

**Issue by bigdwg71** [rigaya/NVEnc#75]
![sei-rbsp-missing](https://user-images.githubusercontent.com/26982284/46051456-9a275180-c107-11e8-81e5-f14306d1abde.PNG)

NVencC encoded 10-bit HDR files get this line in MediaInfo after encoding. The original source 4k HDR file does not show this.

So far it seems like the files are playing and activating HDR on the TV I have to test with, but I am not sure if this RBSP bit could cause issues later on. Just reporting it in case its an easy fix or to get more info on what it means or how to fix it.

Example command that produces file with missing RBSP bit:

NVEncC64.exe --avhw --vbrhq 27000 --codec h265 --preset quality --output-depth 10 --level 5.1 --profile main10 --tier high --lookahead 32 --gop-len 24 --ref 5 --qp-init 1 --vbr-quality 20 --aq --max-bitrate 35000 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --mv-precision Q-pel --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1) --max-cll 1000,1 --crop 0,276,0,276 -i <input> -o <output>

**Comment by bigdwg71** [comment]
Just tested and confirmed the same, using h265 out from NVencC does not show the missing bit, but .mkv out from NVencC does.

My only concern is that it shows SEI which I know is part of the HDR metadata, but all this is ove rmy head. :-)

I did find this about RBSP:

"The bitstream may comprise a sequence of network abstraction layer (NAL) units. Each of the NAL units includes a NAL unit header and encapsulates a raw byte sequence payload (RBSP). The NAL unit header may include a syntax element that indicates a NAL unit type code. The NAL unit type code specified by the NAL unit header of a NAL unit indicates the type of the NAL unit. A RBSP may be a syntax structure containing an integer number of bytes that is encapsulated within a NAL unit. In some instances, an RBSP includes zero bits.

Different types of NAL units may encapsulate different types of RBSPs. For example, a first type of NAL unit may encapsulate a RBSP for a picture parameter set (PPS), a second type of NAL unit may encapsulate a RBSP for a coded slice, a third type of NAL unit may encapsulate a RBSP for Supplemental Enhancement Information (SEI), and so on. A PPS is a syntax structure that may contain syntax elements that apply to zero or more entire coded pictures. NAL units that encapsulate RBSPs for video coding data (as opposed to RBSPs for parameter sets and SEI messages) may be referred to as video coding layer (VCL) NAL units. A NAL unit that encapsulates a coded slice may be referred to herein as a coded slice NAL unit. A RBSP for a coded slice may include a slice header and slice data."

-http://www.freepatentsonline.com/y2017/0085878.html


Doesn't mean much to me though. Thanks for your time.

**Comment by rigaya** [comment]
I think I've found the cause of this issue, and [NVEnc 4.29](https://github.com/rigaya/NVEnc/releases/tag/4.29) shall fix this issue.

**Comment by bigdwg71** [comment]
Thanks for the follow up! I will give it a try and report back.

**Comment by bigdwg71** [comment]
I still see this issue, however, maybe worth  noting that now the error has moved below the HDR metadata rather than on top of it. I will continue to use the .h265 output for now which doesn't seem to show the issue.
![capture](https://user-images.githubusercontent.com/26982284/50529200-468b2200-0ac1-11e9-99da-402e21c202e1.PNG)

**Comment by RukaZhop** [comment]
It's something strange happen when directly encoding to containers (no matter mkv or mp4) with added --master-display and --max-cll parameters... 
I don't know how to explain it straight and clearly, it seems that the first GOP of the encoded file is broken into artifacts:
![Error_thumb](https://user-images.githubusercontent.com/30016532/67423225-884f0100-f5dc-11e9-8acd-841eebe87b87.png)
But if encode to raw h265, and than muxing to mkv through mkvmerge, then everything is fine.

I shared video examples here:
https://1drv.ms/u/s!At27ZwhhgXMCg-1tneHueV0lVOk6GQ?e=T1IdhI

Source.mkv is the original video file that I used for encoding.
Rip.mp4 and Rip.mkv - corrupted files played in MPV video player with artifacts in the first GOP. Furthermore, my smart TV's internal player skip the first GOP of these files, and after some delay start play video from the second GOP.
Rip.h265 is encoded raw hevc stream that i used for create Rip.H265_muxing_with_mkvmerge.mkv file that plays perfectly everywhere.

NVEncC (x64) 4.51 (r1210) by rigaya, Oct  8 2019 12:51:24 (VC 1916/Win/avx2 encoding parameters same for all 'Rip' files except file extension for --output parameter:
` --codec hevc --profile main10 --preset quality --output-depth 10 --vbrhq 0 --vbr-quality 25 --lookahead 32 --ref 4 --bframes 4 --bref-mode middle --aq --mv-precision q-pel --colorprim bt2020 --colormatrix bt2020nc --transfer smpte2084 --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) --max-cll 922,262`

But if we exclude --master-display and --max-cli parameters from the command line than direct encoding to containers (mkv and mp4) produce nice playable files without artifacts in the first GOP...

I also extracted streams from Rip.H265_muxing_with_mkvmerge.mkv and Rip.mkv using the mkvextract tool and compared them with 'fc /b' command. They are slight different:
00000089: 26 4E
0000008B: AF 90
0000008C: 09 04
0000008D: E0 03
0000008E: 3E 9A
0000008F: D0 01
00000090: 3C 06
00000091: 99 89
00000092: D6 18
00000093: D9 33
00000094: 42 C2
00000095: 8B 86
00000096: 5B C4
00000097: 4B 1D
00000098: 08 4C
00000099: AF 0B
0000009A: E5 B8
0000009B: 11 84
0000009C: 0D D0
0000009D: 4C 3E
0000009E: FB 80
0000009F: B3 3D
000000A0: 69 13
000000A1: 32 40
000000A2: F6 42
000000A3: 26 02
000000A4: 55 62
000000A5: C9 5A
000000A6: 7B 00
000000A7: 45 00
000000A8: 68 03
000000A9: 1B 00
000000AA: 73 00
000000AB: 2E 32
000000AC: 5A 80
But how can this be? Does that means that NVenc produce different hevc streams depending on what type of output file is used (h265 or mkv)?

**Comment by pwacooijmans** [comment]
https://github.com/rigaya/NVEnc/issues/51
This explains precisely what's wrong with missing rbsp bit

**Comment by rigaya** [comment]
I think #51 was not the reason.

This issue should be fixed in [NVEnc 4.53](https://github.com/rigaya/NVEnc/releases/tag/4.53).

**Comment by RukaZhop** [comment]
Rigaya, thanks for new version, but direct encoding to containers with --master-display and --max-cll parameters still not working.
When playing in MPV then all frames from first GOP has artifacts as in the picture above in the thread. When play through internal TV's player first GOP just skipped.

**Comment by rigaya** [comment]
I've made another fix in [NVEnc 4.55](https://github.com/rigaya/NVEnc/releases/tag/4.55), this time both the information in MediaInfo and the first GOP seems to be fine.

**Comment by RukaZhop** [comment]
Thanks a lot, Rigaya. 
Version 4.55 fix my issue with broken first GOP when direct encode to containers.

**Comment by rigaya** [comment]
Thanks for confirming, nice to hear that it's fixed!
